Factory/Models/Location.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Location
  {
    public Location()
    {
      this.JoinEntities1 = new HashSet<EngineerLocation>();
      this.JoinEntities2 = new HashSet<MachineLocation>();
    }

    public int LocationId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<EngineerLocation> JoinEntities1 { get; set; } 
    public virtual ICollection<MachineLocation> JoinEntities2 { get; set; }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {

    private readonly FactoryContext _db;
    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer, int MachineId)
    {
      _db.Engineers.Add(engineer);
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
        .Include(engineer => engineer.JoinEntities)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
     return RedirectToAction("Index"); 
    }

    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(joinEntry => joinEntry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddLocation(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.LocationId = new SelectList(_db.Locations, "LocationId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddLocation(Engineer engineer, int LocationId)
    {
      if (LocationId != 0)
      {
        _db.EngineerLocation.Add(new EngineerLocation() { LocationId = LocationId, EngineerId = engineer.EngineerId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteLocation(int joinId)
    {
      var joinEntry = _db.EngineerLocation.FirstOrDefault(joinEntry => joinEntry.EngineerLocationId == joinId);
      _db.EngineerLocation.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/LocationsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  
  public class LocationsController : Controller
  {
    
    private readonly FactoryContext _db;
    public LocationsController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Location> model = _db.Locations.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Location location, int LocationId)
    {
      _db.Locations.Add(location);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisLocation = _db.Locations
        .Include(location => location.JoinEntities1)
        .ThenInclude(join => join.Engineer)
        .Include(location => location.JoinEntities2)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(location => location.LocationId == id);
      return View(thisLocation);
    }

    public ActionResult Edit(int id)
    {
      var thisLocation = _db.Locations.FirstOrDefault(location => location.LocationId == id);
      return View(thisLocation);
    }

    [HttpPost]
    public ActionResult Edit(Location location)
    {
      _db.Entry(location).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisLocation = _db.Locations.FirstOrDefault(location => location.LocationId == id);
      return View(thisLocation);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisLocation = _db.Locations.FirstOrDefault(location => location.LocationId == id);
      _db.Locations.Remove(thisLocation);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      var thisLocation = _db.Locations.FirstOrDefault(location => location.LocationId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisLocation);
    }

    [HttpPost]
    public ActionResult AddMachine(Location location, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.MachineLocation.Add(new MachineLocation() { MachineId = MachineId, LocationId = location.LocationId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.MachineLocation.FirstOrDefault(joinEntry => joinEntry.MachineLocationId == joinId);
      _db.MachineLocation.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id)
    {
      var thisLocation = _db.Locations.FirstOrDefault(location => location.LocationId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisLocation);
    }

    [HttpPost]
    public ActionResult AddEngineer(Location location, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerLocation.Add(new EngineerLocation() { EngineerId = EngineerId, LocationId = location.LocationId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerLocation.FirstOrDefault(joinEntry => joinEntry.EngineerLocationId == joinId);
      _db.EngineerLocation.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

Factory/Views/Locations/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Location

<div class="jumbotron">
  <h1>Assign Engineer to Location here</h1>
</div>
<hr />
<h3>Assign an Engineer to @Html.DisplayFor(model => model.Name)</h3>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.LocationId)
  @Html.Label("Choose Engineer:")
  @Html.DropDownList("EngineerId")
  <br>
  <input type="submit" value="Add to Location" />
}

Factory/Views/Locations/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Location

<div class="jumbotron">
  <h1>Assign Machine to Location here</h1>
</div>
<hr />
<h3>Assign an Machine to @Html.DisplayFor(model => model.Name)</h3>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.LocationId)
  @Html.Label("Choose Machine:")
  @Html.DropDownList("MachineId")
  <br>
  <input type="submit" value="Add to Location" />
}

Factory/Views/Locations/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Location

<div class="jumbotron">
  <h1>Create new Location</h1>
</div>
<hr />
@using (Html.BeginForm())
{
  @Html.Label("Location Name:")
  @Html.TextBoxFor(model => model.Name, new { required = "required" })
  <br>
  <input type="submit" value="Add Machine" />
}

Factory/Views/Locations/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Location

<div class="jumbotron">
  <h1>Delete @Html.DisplayFor(model => model.Name)?</h1>
</div>
<hr />
<div class="row form">
  @using (Html.BeginForm())
  {
    <button class="btn-success" type="submit">Yes</button>
  }
  <button class="btn-danger">@Html.ActionLink("No", "Index")</button>
</div>

Factory/Views/Locations/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Location

<div class="jumbotron">
  <h1>Details for @Html.DisplayFor(model => model.Name):</h1>
</div>
<hr />
<h3>Location Name:</h3>
<p>@Html.DisplayFor(model => model.Name)</p>
<hr />
@if (@Model.JoinEntities1.Count == 0)
{
  <h3>Currently no Engineers at @Html.DisplayFor(model => model.Name).</h3>
}
else
{
  <h3>Engineers at @Html.DisplayFor(model => model.Name):</h3>
  <ul>
    @foreach (var EngineerLocation in @Model.JoinEntities1)
    {
      <li>@Html.ActionLink(@EngineerLocation.Engineer.Name, "Details", "Engineers", new { id = EngineerLocation.Engineer.EngineerId })</li>
    }
  </ul>
}
@if (@Model.JoinEntities1.Count == 0)
{
  <h3>No Engineers to Remove from this Location</h3>
}
else
{
<h3>Delete Engineer from @Html.DisplayFor(model => model.Name)</h3>
<ul>
  <div class="row">
  @foreach (var join in Model.JoinEntities1)
  {
    @using (Html.BeginForm("DeleteEngineer", "Locations"))
    {
      @Html.Hidden("joinId", @join.EngineerLocationId)
      <button class="btn" type="submit">@join.Engineer.Name</button>
    }
  }
  </div>
</ul>
}
<hr />
@if (@Model.JoinEntities2.Count == 0)
{
  <h3>Currently no Machines at @Html.DisplayFor(model => model.Name).</h3>
}
else
{
  <h3>Machines at @Html.DisplayFor(model => model.Name):</h3>
  <ul>
    @foreach (var MachineLocation in @Model.JoinEntities2)
    {
      <li>@Html.ActionLink(@MachineLocation.Machine.Name, "Details", "Machiness", new { id = MachineLocation.Machine.MachineId })</li>
    }
  </ul>
}
@if (@Model.JoinEntities2.Count == 0)
{
  <h3>No Engineers to Remove from this Location</h3>
}
else
{
<h3>Delete Machine from @Html.DisplayFor(model => model.Name)</h3>
<ul>
  <div class="row">
  @foreach (var join in Model.JoinEntities2)
  {
    @using (Html.BeginForm("DeleteMachine", "Locations"))
    {
      @Html.Hidden("joinId", @join.MachineLocationId)
      <button class="btn" type="submit">@join.Machine.Name</button>
    }
  }
  </div>
</ul>
}
<hr />
<button class="btn">@Html.ActionLink("Edit Location", "Edit", new { id = Model.LocationId })</button>
<button class="btn">@Html.ActionLink("Delete Location", "Delete", new { id = Model.LocationId })</button>
<button class="btn">@Html.ActionLink("Add Engineer to Location", "AddEngineer", "Locations", new { id = Model.LocationId })</button>
<button class="btn">@Html.ActionLink("Add Machine to Location", "AddMachine", "Locations", new { id = Model.LocationId })</button>

Factory/Views/Locations/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Location

<div class="jumbotron">
  <h1>Edit @Html.DisplayFor(model => model.Name)</h1>
</div>
<hr />
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.LocationId)
  @Html.Label("Update Location Name:")
  @Html.EditorFor(model => model.Name)
  <br>
  <input type="submit" value="Update Location" />
}

Factory/Views/Locations/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models

<div class="jumbotron">
  <h1>Locations</h1>
</div>
<hr />
@if (@Model.Count == 0)
{
  <h3>There are no Locations, this is a remote machine fixing job!</h3>
}
<ul>
  @foreach(Location location in Model)
  {
    <li>@Html.ActionLink($"{location.Name}", "Details", new { id = location.LocationId })</li>
  }
</ul>
<hr />
<button class="btn">@Html.ActionLink("Add New Location", "Create")</button>